name: Java CI

on:
  push:
    branches:
      - master
      - sonarcloud
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Scan with SonarCloud
        run: mvn verify sonar:sonar -Dsonar.login=${{ secrets.SONARCLOUD }}
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            JAVA_HOME: ''
